mxid: ""
device_id: ""
access_token: ""
homeserver: https://matrix-client.matrix.org
room_cache_size: 32
room_cache_age: 60
notify_sound: true
send_to_verified_only: false
data_dir: /home/david/.local/share/gomuks
cache_dir: /home/david/.cache/gomuks
history_path: /home/david/.cache/gomuks/history.db
room_list_path: /home/david/.cache/gomuks/rooms.gob.gz
media_dir: /home/david/.cache/gomuks/media
download_dir: /home/david/Downloads
state_dir: /home/david/.cache/gomuks/state
